"""Data model for categories."""

from app.model import db
import app.controller.utils as utils


definition = {
    'types': {
        'name': [str],
        'description': [str, type(None)]
    },
    'required': ['name'],
    'unique': ['name']
}


class Category(db.Model):
    """
    Data model for categories.

    Attributes
    ----------
    id : int
    name : str
    description : str
    items : list
        Auto generated by SQLAlchemy

    """

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True, nullable=False)
    description = db.Column(db.Text)
    items = db.relationship('Item', backref='category', lazy=True)

    def to_dict(self) -> dict:
        """Return a Category object formatted as dict."""
        obj = {
            "id": self.id,
            "name": self.name,
            "description": self.description
        }
        return obj

    def from_dict(self, data: dict, new: bool = False):
        """Fill Category attributes from given dictionary."""
        for field in ['name', 'description']:
            if field in data:
                setattr(self, field, data[field])

    @staticmethod
    def check_data(data: dict, new: bool = False):
        """Verify Category data for correct keys and types."""
        error = utils.check_data(data, definition, new)
        return error
