"""empty message

Revision ID: aae0c3ad32aa
Revises: 4ef7ee6f5982
Create Date: 2018-12-08 13:49:59.036363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae0c3ad32aa'
down_revision = '4ef7ee6f5982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thirdparty', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thirdparty', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
